apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 67.0.0
    helm:
      values: |
        grafana:
          adminPassword: admin
          service:
            type: ClusterIP

          # add this to replace the need for extra-datasources ConfigMap
          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki-gateway.monitoring.svc.cluster.local
              isDefault: false

            - name: Tempo
              type: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3200
              jsonData:
                tracesToLogs:
                  datasourceUid: "Loki"
                  spanStartTimeShift: "1h"
                  spanEndTimeShift: "1h"
                  filterByTraceID: true

            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-operated.monitoring.svc.cluster.local:9090
              isDefault: true

          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: false # 👈 disable this, we don’t need the sidecar for datasources
            defaultDashboardsEnabled: true
            defaultDatasourcesEnabled: false

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
      - SkipCRDs=true


