apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default # belongs to argocd's default project
  destination:
    name: in-cluster # deploy to the same k8s cluster where argocd is installed
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack # this chart contains & installs prometheus, grafana, and alertmanager
    targetRevision: 67.0.0
    helm:
      values: |
        grafana:
          adminPassword: admin
          service:
            type: ClusterIP
          sidecar:
            dashboards:
              enabled: true
            datasources:
              enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true
      - SkipCRDs=true   