# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-prometheus-stack
#   namespace: argocd
# spec:
#   project: default
#   destination:
#     name: in-cluster
#     namespace: monitoring
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     chart: kube-prometheus-stack
#     targetRevision: 67.0.0
#     helm:
#       values: |
#         grafana:
#           adminPassword: admin
#           service:
#             type: ClusterIP
#           sidecar:
#             dashboards:
#               enabled: true
#             datasources:
#               enabled: true
#           defaultDashboardsEnabled: true
#           defaultDatasourcesEnabled: false

#           additionalDataSources:
#             - name: Loki
#               type: loki
#               access: proxy
#               url: http://loki-gateway.monitoring.svc.cluster.local
#               isDefault: false

#             - name: Tempo
#               type: tempo
#               access: proxy
#               url: http://tempo.monitoring.svc.cluster.local:3200
#               jsonData:
#                 tracesToLogs:
#                   datasourceUid: "Loki"
#                   spanStartTimeShift: "1h"
#                   spanEndTimeShift: "1h"
#                   filterByTraceID: true

#             - name: Prometheus
#               type: prometheus
#               access: proxy
#               url: http://kube-prometheus-stack-prometheus.monitoring:9090
#               isDefault: true

#             - name: Alertmanager
#               type: alertmanager
#               access: proxy
#               url: http://kube-prometheus-stack-alertmanager.monitoring:9093
#               jsonData:
#                 handleGrafanaManagedAlerts: false
#                 implementation: prometheus

#         prometheus:
#           prometheusSpec:
#             serviceMonitorSelectorNilUsesHelmValues: false
#             podMonitorSelectorNilUsesHelmValues: false

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - PruneLast=true
#       - ServerSideApply=true
#       - SkipCRDs=true


# # apiVersion: argoproj.io/v1alpha1
# # kind: Application
# # metadata:
# #   name: kube-prometheus-stack
# #   namespace: argocd
# # spec:
# #   project: default
# #   destination:
# #     name: in-cluster
# #     namespace: monitoring
# #   source:
# #     repoURL: https://prometheus-community.github.io/helm-charts
# #     chart: kube-prometheus-stack
# #     targetRevision: 67.0.0
# #     helm:
# #     values: |
# #       grafana:
# #         adminPassword: admin
# #         service:
# #           type: ClusterIP
# #         sidecar:
# #           dashboards:
# #             enabled: true
# #           datasources:
# #             enabled: true
# #           # disable Helm’s default datasources so we control them ourselves
# #           defaultDatasourcesEnabled: false

# #         additionalDataSources:
# #           - name: Loki
# #             type: loki
# #             access: proxy
# #             url: http://loki-gateway.monitoring.svc.cluster.local
# #             isDefault: false

# #           - name: Tempo
# #             type: tempo
# #             access: proxy
# #             url: http://tempo.monitoring.svc.cluster.local:3200
# #             jsonData:
# #               tracesToLogs:
# #                 datasourceUid: "Loki"
# #                 spanStartTimeShift: "1h"
# #                 spanEndTimeShift: "1h"
# #                 filterByTraceID: true

# #           - name: Prometheus
# #             type: prometheus
# #             access: proxy
# #             url: http://kube-prometheus-stack-prometheus.monitoring:9090
# #             isDefault: true

# #           - name: Alertmanager
# #             type: alertmanager
# #             access: proxy
# #             url: http://kube-prometheus-stack-alertmanager.monitoring:9093
# #             jsonData:
# #               handleGrafanaManagedAlerts: false
# #               implementation: prometheus


# #     # helm:
# #     #   values: |
# #     #     grafana:
# #     #       adminPassword: admin
# #     #       service:
# #     #         type: ClusterIP
# #     #       sidecar:
# #     #         dashboards:
# #     #           enabled: true
# #     #         datasources:
# #     #           enabled: true 
# #     #         # defaultDashboardsEnabled: true
# #     #         defaultDatasourcesEnabled: false

# #     #     prometheus:
# #     #       prometheusSpec:
# #     #         serviceMonitorSelectorNilUsesHelmValues: false
# #     #         podMonitorSelectorNilUsesHelmValues: false
  
# #   syncPolicy:
# #     automated:
# #       prune: true
# #       selfHeal: true
# #     syncOptions:
# #       - CreateNamespace=true
# #       - PruneLast=true
# #       - ServerSideApply=true
# #       - SkipCRDs=true


