apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
        env:
        - name: VAULT_ADDR
          value: "http://135.233.112.30:8200"
        - name: VAULT_ROLE_ID
          value: "9055720e-3c61-aa32-90a7-492e3a9f5759"
        - name: VAULT_SECRET_ID
          value: "bc6162ef-da1f-013f-0d66-a1a8977c43d6"

        - name: OTEL_SERVICE_NAME
          value: "student-progress"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"

        # env:
        # - name: VAULT_ADDR
        #   valueFrom:
        #    secretKeyRef:
        #      name: {{ .Values.secret.name }}
        #      key: VAULT_ADDR

        # - name: VAULT_SECRET_ID
        #   valueFrom:
        #    secretKeyRef:
        #      name: {{ .Values.secret.name }}
        #      key: VAULT_SECRET_ID

        # - name: VAULT_ROLE_ID
        #   valueFrom:
        #    secretKeyRef:
        #      name: {{ .Values.secret.name }}
        #      key: VAULT_ROLE_ID

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
