apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (printf "%s-service" .Values.app.name) }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

